backend:
  name: github
  repo: igorflady/Flady_site
  branch: main
  base_url: https://flady-site.vercel.app
  auth_endpoint: api/begin

media_folder: "imagens/uploads"
public_folder: "/imagens/uploads"

locale: "pt"

collections:

  - name: "artigos"
    label: "Artigos"
    folder: "conteudo/artigos"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    fields:
      - label: "Título"
        name: "title"
        widget: "string"

      - label: "Data de publicação"
        name: "date"
        widget: "datetime"

      - label: "Categorias principais"
        name: "categories"
        widget: "relation"
        collection: "categorias"
        search_fields:
          - "nome"
        value_field: "nome"
        display_fields:
          - "nome"
        multiple: true
        min: 1
        hint: "Escolha uma ou mais categorias às quais este conteúdo pertence diretamente."

      - label: "Temas relacionados"
        name: "related_categories"
        widget: "relation"
        collection: "categorias"
        search_fields:
          - "nome"
        value_field: "nome"
        display_fields:
          - "nome"
        multiple: true
        required: false
        hint: "Escolha temas que tenham relação com o conteúdo, mesmo que não sejam o foco principal."

      - label: "Descrição"
        name: "description"
        widget: "text"

      - label: "Imagem de capa"
        name: "image"
        widget: "image"
        required: false

      - label: "Arquivo PDF"
        name: "pdf"
        widget: "file"
        required: false
        hint: "Opcional. Anexe um artigo, pesquisa ou outro documento em PDF."

      - label: "Artigo em destaque"
        name: "featured"
        widget: "boolean"
        default: false

      - label: "Conteúdo do artigo"
        name: "body"
        widget: "markdown"
        required: false
        hint: "Escreva o conteúdo completo ou uma apresentação/resumo caso tenha anexado um PDF."


  - name: "categorias"
    label: "Categorias"
    folder: "conteudo/categorias"
    create: true
    slug: "{{slug}}"

    fields:
      - label: "Nome da categoria"
        name: "nome"
        widget: "string"

      - label: "Descrição"
        name: "descricao"
        widget: "text"
        required: false

      - label: "Ícone"
        name: "icone"
        widget: "string"
        required: false
        hint: "Você pode adicionar um símbolo ou emoji para representar esta categoria."


  - name: "contatos"
    label: "Contatos e redes sociais"
    folder: "conteudo/contatos"
    create: true
    slug: "{{slug}}"

    fields:
      - label: "Nome"
        name: "nome"
        widget: "string"
        hint: "Exemplo: Instagram, LinkedIn, E-mail ou outra rede."

      - label: "Imagem ou ícone"
        name: "imagem"
        widget: "image"
        required: false
        hint: "Adicione uma imagem ou ícone para representar este contato."

      - label: "Link"
        name: "link"
        widget: "string"
        hint: "Adicione o endereço completo do seu perfil ou página."

      - label: "Texto complementar"
        name: "descricao"
        widget: "string"
        required: false
        hint: "Opcional. Exemplo: @seuusuario ou uma breve identificação."
